plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.24'
}

group = 'analytics.harness'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'com.github.ht-sdks.events-sdk-kotlin:core:7fe50c7'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit'
}

tasks.named('test', Test) {
    useJUnit()
}
