import {
  renderAndroid,
  MIN_SDK_PACKAGE,
  MIN_SDK_VERSION,
} from '../src/render/android';
import { eventsFromFixture } from './helpers/fixtures';
import type { NormalizedEvent } from '../src/normalize/types';

describe('renderAndroid', () => {
  it.each(['simple-track.json', 'multi-version.json', 'with-refs.json'])(
    'matches the snapshot for %s',
    async (file) => {
      const src = await renderAndroid(eventsFromFixture(file));
      expect(src).toMatchSnapshot();
    },
  );

  it('emits a generated header with CLI and SDK versions', async () => {
    const src = await renderAndroid(eventsFromFixture('simple-track.json'));
    expect(src).toContain(
      'Generated by @ht-sdks/events-cli@0.1.0 — do not edit.',
    );
    expect(src).toContain(
      `Requires peer ${MIN_SDK_PACKAGE} v${MIN_SDK_VERSION} or later.`,
    );
  });

  it('emits package analytics and class HtEvents by default', async () => {
    const src = await renderAndroid(eventsFromFixture('simple-track.json'));
    expect(src).toContain('package analytics;');
    expect(src).toContain('public final class HtEvents');
    expect(src).toContain('analytics.track(');
  });

  it('derives package and class from a custom output path', async () => {
    const src = await renderAndroid(
      eventsFromFixture('simple-track.json'),
      './src/main/java/com/example/events/Generated.java',
    );
    expect(src).toContain('package com.example.events;');
    expect(src).toContain('public final class Generated');
    expect(src).not.toContain('package analytics;');
  });

  it('sorts events by wrapperName', async () => {
    const events = eventsFromFixture('multi-version.json').reverse();
    const src = await renderAndroid(events);
    const v1 = src.indexOf('trackOrderCompletedV1(');
    const v2 = src.indexOf('trackOrderCompletedV2(');
    expect(v1).toBeGreaterThan(-1);
    expect(v2).toBeGreaterThan(-1);
    expect(v1).toBeLessThan(v2);
  });

  it('emits alias wrappers with newId, not a properties payload', async () => {
    const event: NormalizedEvent = {
      type: 'alias',
      version: 'default',
      domainName: 'Users',
      envelopeKey: 'properties',
      schema: { type: 'object' },
      wrapperName: 'aliasDefault',
    };
    const src = await renderAndroid([event]);
    expect(src).toContain(
      'public void aliasDefault(String newId, Options options)',
    );
    expect(src).toContain('analytics.alias(newId, injected.options);');
    expect(src).not.toMatch(/aliasDefault\(.*properties/);
  });

  it('maps page events to screen', async () => {
    const event: NormalizedEvent = {
      type: 'page',
      name: 'Home',
      version: 'default',
      domainName: 'Web',
      envelopeKey: 'properties',
      schema: {
        type: 'object',
        properties: { path: { type: 'string' } },
      },
      wrapperName: 'pageHomeDefault',
    };
    const src = await renderAndroid([event]);
    expect(src).toContain('analytics.screen(null, "Home"');
    expect(src).not.toContain('analytics.page(');
  });

  it('emits a latest-version alias method', async () => {
    const src = await renderAndroid(eventsFromFixture('multi-version.json'));
    expect(src).toContain(
      'public void trackOrderCompleted(TrackOrderCompletedV2 properties, Options options)',
    );
    expect(src).toContain('trackOrderCompletedV2(properties, options);');
  });

  it('fails when generated method names collide', async () => {
    const events: NormalizedEvent[] = [
      {
        type: 'track',
        name: 'Foo',
        version: 'v1',
        domainName: 'A',
        envelopeKey: 'properties',
        schema: { type: 'object' },
        wrapperName: 'trackFoo',
        latestAlias: 'trackFoo',
      },
    ];
    await expect(renderAndroid(events)).rejects.toThrow(
      /Android identifier collision/,
    );
  });
});
