import {
  renderKotlin,
  MIN_SDK_PACKAGE,
  MIN_SDK_VERSION,
} from '../src/render/kotlin';
import { eventsFromFixture } from './helpers/fixtures';
import type { NormalizedEvent } from '../src/normalize/types';

describe('renderKotlin', () => {
  it.each(['simple-track.json', 'multi-version.json', 'with-refs.json'])(
    'matches the snapshot for %s',
    async (file) => {
      const src = await renderKotlin(eventsFromFixture(file));
      expect(src).toMatchSnapshot();
    },
  );

  it('emits a generated header with CLI and SDK versions', async () => {
    const src = await renderKotlin(eventsFromFixture('simple-track.json'));
    expect(src).toContain(
      'Generated by @ht-sdks/events-cli@0.1.0 — do not edit.',
    );
    expect(src).toContain(
      `Requires peer ${MIN_SDK_PACKAGE} v${MIN_SDK_VERSION} or later.`,
    );
  });

  it('emits package analytics and class HtEvents by default', async () => {
    const src = await renderKotlin(eventsFromFixture('simple-track.json'));
    expect(src).toContain('package analytics');
    expect(src).toContain('class HtEvents');
    expect(src).toContain('analytics.track(');
  });

  it('derives package and class from a custom output path', async () => {
    const src = await renderKotlin(
      eventsFromFixture('simple-track.json'),
      './src/main/kotlin/com/example/events/Generated.kt',
    );
    expect(src).toContain('package com.example.events');
    expect(src).toContain('class Generated');
    expect(src).toContain(
      'if (value::class.java.enclosingClass == Generated::class.java)',
    );
    expect(src).not.toContain('package analytics\n');
    expect(src).not.toContain('class HtEvents');
  });

  it('sorts events by wrapperName', async () => {
    const events = eventsFromFixture('multi-version.json').reverse();
    const src = await renderKotlin(events);
    const v1 = src.indexOf('fun trackOrderCompletedV1(');
    const v2 = src.indexOf('fun trackOrderCompletedV2(');
    expect(v1).toBeGreaterThan(-1);
    expect(v2).toBeGreaterThan(-1);
    expect(v1).toBeLessThan(v2);
  });

  it('emits alias wrappers with newId, not a properties payload', async () => {
    const event: NormalizedEvent = {
      type: 'alias',
      version: 'default',
      domainName: 'Users',
      envelopeKey: 'properties',
      schema: { type: 'object' },
      wrapperName: 'aliasDefault',
    };
    const src = await renderKotlin([event]);
    expect(src).toContain(
      'fun aliasDefault(newId: String, context: Map<String, Any>? = null)',
    );
    expect(src).toContain(
      'analytics.alias(newId, contextEnrichment(injected.context))',
    );
    expect(src).not.toMatch(/fun aliasDefault\(.*properties/);
  });

  it('maps page events to screen', async () => {
    const event: NormalizedEvent = {
      type: 'page',
      name: 'Home',
      version: 'default',
      domainName: 'Web',
      envelopeKey: 'properties',
      schema: {
        type: 'object',
        properties: { path: { type: 'string' } },
      },
      wrapperName: 'pageHomeDefault',
    };
    const src = await renderKotlin([event]);
    expect(src).toContain('analytics.screen("Home"');
    expect(src).not.toContain('analytics.page(');
  });

  it('emits a latest-version alias function', async () => {
    const src = await renderKotlin(eventsFromFixture('multi-version.json'));
    expect(src).toContain(
      'fun trackOrderCompleted(properties: TrackOrderCompletedV2, context: Map<String, Any>? = null)',
    );
    expect(src).toContain('trackOrderCompletedV2(properties, context)');
  });

  it('fails when generated method names collide', async () => {
    const events: NormalizedEvent[] = [
      {
        type: 'track',
        name: 'Foo',
        version: 'v1',
        domainName: 'A',
        envelopeKey: 'properties',
        schema: { type: 'object' },
        wrapperName: 'trackFoo',
        latestAlias: 'trackFoo',
      },
    ];
    await expect(renderKotlin(events)).rejects.toThrow(
      /Kotlin identifier collision/,
    );
  });
});
