import {
  renderJava,
  MIN_SDK_PACKAGE,
  MIN_SDK_VERSION,
} from '../src/render/java';
import { eventsFromFixture } from './helpers/fixtures';
import type { NormalizedEvent } from '../src/normalize/types';

describe('renderJava', () => {
  it.each(['simple-track.json', 'multi-version.json', 'with-refs.json'])(
    'matches the snapshot for %s',
    async (file) => {
      const src = await renderJava(eventsFromFixture(file));
      expect(src).toMatchSnapshot();
    },
  );

  it('emits a generated header with CLI and SDK versions', async () => {
    const src = await renderJava(eventsFromFixture('simple-track.json'));
    expect(src).toContain(
      'Generated by @ht-sdks/events-cli@0.1.0 — do not edit.',
    );
    expect(src).toContain(
      `Requires peer ${MIN_SDK_PACKAGE} v${MIN_SDK_VERSION} or later.`,
    );
  });

  it('emits package analytics and enqueue-based peer SDK imports', async () => {
    const src = await renderJava(eventsFromFixture('simple-track.json'));
    expect(src).toContain('package analytics;');
    expect(src).toContain('import com.hightouch.analytics.Analytics;');
    expect(src).toContain(
      'import com.hightouch.analytics.messages.TrackMessage;',
    );
    expect(src).toContain('public final class HtEvents');
    expect(src).toContain('analytics.enqueue(');
  });

  it('emits camelCase methods and PascalCase payload types', async () => {
    const src = await renderJava(eventsFromFixture('simple-track.json'));
    expect(src).toMatch(/public static final class TrackOrderCompletedDefault/);
    expect(src).toMatch(
      /public void trackOrderCompletedDefault\(String userId, TrackOrderCompletedDefault properties, Map<String, \?> context\)/,
    );
    expect(src).toContain('TrackMessage.builder(');
  });

  it('sorts events by wrapperName', async () => {
    const events = eventsFromFixture('multi-version.json').reverse();
    const src = await renderJava(events);
    const v1 = src.indexOf('public void trackOrderCompletedV1(');
    const v2 = src.indexOf('public void trackOrderCompletedV2(');
    expect(v1).toBeGreaterThan(-1);
    expect(v2).toBeGreaterThan(-1);
    expect(v1).toBeLessThan(v2);
  });

  it('pins quicktype title to the wrapper type name', async () => {
    const event: NormalizedEvent = {
      type: 'track',
      name: 'Order Completed',
      version: 'v1',
      domainName: 'Orders',
      envelopeKey: 'properties',
      schema: {
        type: 'object',
        title: 'WrongTitle',
        properties: { orderId: { type: 'string' } },
      },
      wrapperName: 'trackOrderCompletedV1',
    };
    const src = await renderJava([event]);
    expect(src).toMatch(/public static final class TrackOrderCompletedV1/);
    expect(src).not.toMatch(/class WrongTitle/);
  });

  it('emits alias wrappers with userId and previousId, not a properties payload', async () => {
    const event: NormalizedEvent = {
      type: 'alias',
      version: 'default',
      domainName: 'Users',
      envelopeKey: 'properties',
      schema: { type: 'object' },
      wrapperName: 'aliasDefault',
    };
    const src = await renderJava([event]);
    expect(src).toContain(
      'public void aliasDefault(String userId, String previousId, Map<String, ?> context)',
    );
    expect(src).toContain('AliasMessage.builder(previousId).userId(userId)');
    expect(src).not.toMatch(/void aliasDefault\([^)]*properties/);
  });

  it('keeps page events as page, not screen', async () => {
    const event: NormalizedEvent = {
      type: 'page',
      name: 'Home',
      version: 'default',
      domainName: 'Web',
      envelopeKey: 'properties',
      schema: {
        type: 'object',
        properties: { path: { type: 'string' } },
      },
      wrapperName: 'pageHomeDefault',
    };
    const src = await renderJava([event]);
    expect(src).toContain('PageMessage.builder("Home")');
    expect(src).not.toMatch(/ScreenMessage\.builder\("Home"\)/);
    expect(src).not.toMatch(/TrackMessage\.builder\("Home"\)/);
  });

  it('emits a latest-version alias function', async () => {
    const src = await renderJava(eventsFromFixture('multi-version.json'));
    expect(src).toContain(
      'public void trackOrderCompleted(String userId, TrackOrderCompletedV2 properties, Map<String, ?> context)',
    );
    expect(src).toContain(
      'trackOrderCompletedV2(userId, properties, context);',
    );
  });

  it('fails when generated method names collide', async () => {
    const events: NormalizedEvent[] = [
      {
        type: 'track',
        name: 'Foo',
        version: 'v1',
        domainName: 'A',
        envelopeKey: 'properties',
        schema: { type: 'object' },
        wrapperName: 'trackFoo',
        latestAlias: 'trackFoo',
      },
    ];
    await expect(renderJava(events)).rejects.toThrow(
      /Java identifier collision/,
    );
  });
});
