import type { NormalizedEvent } from '../../normalize/types';
import {
  assertJvmCollisions,
  methodName,
  typeNameFor,
} from '../shared/jvm-names';

export { methodName, typeNameFor };

const JAVA_KEYWORDS = [
  'abstract',
  'assert',
  'boolean',
  'break',
  'byte',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'double',
  'else',
  'enum',
  'extends',
  'final',
  'finally',
  'float',
  'for',
  'goto',
  'if',
  'implements',
  'import',
  'instanceof',
  'int',
  'interface',
  'long',
  'native',
  'new',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'static',
  'strictfp',
  'super',
  'switch',
  'synchronized',
  'this',
  'throw',
  'throws',
  'transient',
  'try',
  'void',
  'volatile',
  'while',
  'true',
  'false',
  'null',
  '_',
];

export function assertNoMethodCollisions(
  events: readonly NormalizedEvent[],
  className: string,
): void {
  assertJvmCollisions(events, {
    label: 'Java',
    reserved: new Set([
      className,
      'Injected',
      'Analytics',
      'TrackMessage',
      'IdentifyMessage',
      'GroupMessage',
      'PageMessage',
      'ScreenMessage',
      'AliasMessage',
      'Object',
      'Class',
      'String',
      'List',
      'Map',
      ...JAVA_KEYWORDS,
    ]),
    typeKey: (name) => name.toLowerCase(),
  });
}
