import type { NormalizedEvent } from '../../src/normalize/types';

/** Extra contracts for language harnesses. Domain fixtures omit some event types. */
export function extraHarnessEvents(): NormalizedEvent[] {
  return [
    {
      type: 'group',
      version: 'default',
      domainName: 'Accounts',
      envelopeKey: 'traits',
      schema: {
        type: 'object',
        properties: { name: { type: 'string' } },
      },
      wrapperName: 'groupDefault',
      latestAlias: 'group',
    },
    {
      type: 'alias',
      version: 'default',
      domainName: 'Users',
      envelopeKey: 'properties',
      schema: { type: 'object' },
      wrapperName: 'aliasDefault',
      latestAlias: 'alias',
    },
    {
      type: 'page',
      name: 'Home',
      version: 'default',
      domainName: 'Web',
      envelopeKey: 'properties',
      schema: {
        type: 'object',
        properties: { path: { type: 'string' } },
      },
      wrapperName: 'pageHomeDefault',
      latestAlias: 'pageHome',
    },
    {
      type: 'screen',
      name: 'Home',
      version: 'default',
      domainName: 'Mobile',
      envelopeKey: 'properties',
      schema: {
        type: 'object',
        properties: { path: { type: 'string' } },
      },
      wrapperName: 'screenHomeDefault',
      latestAlias: 'screenHome',
    },
    {
      type: 'track',
      name: 'Order Completed',
      version: 'v1',
      domainName: 'OrdersProps',
      envelopeKey: 'properties',
      schemaVersionPath: ['properties', 'apiVersion'],
      schema: {
        type: 'object',
        properties: { orderId: { type: 'string' } },
      },
      wrapperName: 'trackOrderCompletedPropsV1',
      latestAlias: 'trackOrderCompletedProps',
    },
    {
      type: 'identify',
      version: 'v1',
      domainName: 'UsersTraits',
      envelopeKey: 'traits',
      schemaVersionPath: ['traits', 'apiVersion'],
      schema: {
        type: 'object',
        properties: { email: { type: 'string' } },
      },
      wrapperName: 'identifyTraitsV1',
    },
    {
      type: 'identify',
      version: 'v1',
      domainName: 'UsersWrongEnvelope',
      envelopeKey: 'traits',
      schemaVersionPath: ['properties', 'apiVersion'],
      schema: {
        type: 'object',
        properties: { email: { type: 'string' } },
      },
      wrapperName: 'identifyWrongEnvelopeV1',
    },
    {
      type: 'track',
      name: 'Order Completed',
      version: 'v1',
      domainName: 'OrdersWrongEnvelope',
      envelopeKey: 'properties',
      schemaVersionPath: ['traits', 'apiVersion'],
      schema: {
        type: 'object',
        properties: { orderId: { type: 'string' } },
      },
      wrapperName: 'trackWrongEnvelopeV1',
    },
    {
      type: 'alias',
      version: 'v1',
      domainName: 'UsersAliasCtx',
      envelopeKey: 'properties',
      schemaVersionPath: ['context', 'protocols', 'schemaVersion'],
      schema: { type: 'object' },
      wrapperName: 'aliasContextV1',
    },
    {
      type: 'alias',
      version: 'v1',
      domainName: 'UsersAliasProps',
      envelopeKey: 'properties',
      schemaVersionPath: ['properties', 'apiVersion'],
      schema: { type: 'object' },
      wrapperName: 'aliasPropsV1',
    },
    {
      type: 'track',
      name: 'Signed Up',
      version: 'default',
      domainName: 'Auth',
      envelopeKey: 'properties',
      schemaVersionPath: ['context', 'protocols', 'schemaVersion'],
      schema: {
        type: 'object',
        properties: { plan: { type: 'string' } },
      },
      wrapperName: 'trackSignedUpDefault',
      latestAlias: 'trackSignedUp',
    },
  ];
}
