import { cliPackage } from '../../lib/package-info';

export function headerLines(
  peerPackage: string,
  peerVersion: string,
): { generated: string; requires: string } {
  const { name, version } = cliPackage();
  return {
    generated: `Generated by ${name}@${version} — do not edit.`,
    requires: `Requires peer ${peerPackage} v${peerVersion} or later.`,
  };
}

/** `//` line comments. JSDoc (browser-ts) stays in that renderer. */
export function renderSlashHeader(
  peerPackage: string,
  peerVersion: string,
): string {
  const { generated, requires } = headerLines(peerPackage, peerVersion);
  return [`// ${generated}`, `// ${requires}`].join('\n');
}
