import { cliPackage } from '../../lib/package-info';

export function headerLines(
  peerPackage: string,
  peerVersion: string,
): { generated: string; requires: string } {
  const { name, version } = cliPackage();
  return {
    generated: `Generated by ${name}@${version} — do not edit.`,
    requires: `Requires peer ${peerPackage}@^${peerVersion} or later.`,
  };
}
