import { MIN_SDK_PACKAGE, MIN_SDK_VERSION } from './constants';
import { cliPackage } from '../../lib/package-info';

export function renderHeader(): string {
  const { name, version } = cliPackage();
  return [
    '/**',
    ` * Generated by ${name}@${version} — do not edit.`,
    ` * Requires peer ${MIN_SDK_PACKAGE}@^${MIN_SDK_VERSION} or later.`,
    ' */',
  ].join('\n');
}
