import type { NormalizedEvent } from '../../src/normalize/types';
import { eventsFromFixture } from './fixtures';

const SNAPSHOT_FIXTURES = [
  'simple-track.json',
  'multi-version.json',
  'with-refs.json',
] as const;

export type RendererContractTests = {
  render: (events: NormalizedEvent[]) => Promise<string>;
  peerPackage: string;
  peerVersion: string;
  /**
   * Substring that locates this wrapper in generated source for the sort
   * check. Must not match an earlier type name (Go: `func TrackFoo(`).
   */
  sortedWrapperSnippet: (wrapperName: string) => string;
};

/** Snapshots, generated header, and wrapperName sort. Language asserts stay in the SDK test file. */
export function defineRendererContractTests(opts: RendererContractTests): void {
  it.each([...SNAPSHOT_FIXTURES])(
    'matches the snapshot for %s',
    async (file) => {
      const src = await opts.render(eventsFromFixture(file));
      expect(src).toMatchSnapshot();
    },
  );

  it('emits a generated header with CLI and SDK versions', async () => {
    const src = await opts.render(eventsFromFixture('simple-track.json'));
    expect(src).toContain(
      'Generated by @ht-sdks/events-cli@0.1.0 — do not edit.',
    );
    expect(src).toContain(
      `Requires peer ${opts.peerPackage} v${opts.peerVersion} or later.`,
    );
  });

  it('sorts events by wrapperName', async () => {
    const events = eventsFromFixture('multi-version.json').reverse();
    const src = await opts.render(events);
    const v1 = src.indexOf(opts.sortedWrapperSnippet('trackOrderCompletedV1'));
    const v2 = src.indexOf(opts.sortedWrapperSnippet('trackOrderCompletedV2'));
    expect(v1).toBeGreaterThan(-1);
    expect(v2).toBeGreaterThan(-1);
    expect(v1).toBeLessThan(v2);
  });
}
