import type { NormalizedEvent } from '../../normalize/types';
import type { ArtifactFile } from '../shared/output';
import { JsonNamePhpTargetLanguage } from '../shared/php-json-name-quicktype';
import { runQuicktype } from '../shared/quicktype-input';
import { typeNameFor } from './names';
import { phpFilePreamble } from './preamble';

function splitClasses(source: string): { name: string; body: string }[] {
  const cleaned = source
    .replace(/^<\?php\s*/g, '')
    .replace(/^\/\/ This is an autogenerated file:.*$/gm, '')
    .trim();
  if (cleaned.length === 0) {
    return [];
  }
  return cleaned
    .split(/(?=^class )/m)
    .map((part) => part.trim())
    .filter((part) => part.length > 0)
    .map((body) => {
      const match = /^class (\w+)/.exec(body);
      if (match === null) {
        throw new Error(`quicktype PHP output missing class name:\n${body}`);
      }
      return { name: match[1], body };
    });
}

function wrapClass(body: string): string {
  return `${phpFilePreamble()}namespace Hightouch\\Generated;\n\n${body}\n`;
}

export async function renderTypes(
  events: NormalizedEvent[],
): Promise<ArtifactFile[]> {
  const payloadEvents = events.filter((event) => event.type !== 'alias');
  const types =
    payloadEvents.length === 0
      ? ''
      : await runQuicktype(payloadEvents, {
          typeNameFor,
          lang: 'php',
          language: new JsonNamePhpTargetLanguage(),
          rendererOptions: {
            'with-get': 'false',
            'with-set': 'false',
            'acronym-style': 'original' as never,
          },
        });
  const classes = splitClasses(types);
  const declared = new Set(classes.map((entry) => entry.name));
  const files = classes.map((entry) => ({
    path: `${entry.name}.php`,
    contents: wrapClass(entry.body),
  }));
  for (const event of payloadEvents) {
    const name = typeNameFor(event);
    if (!declared.has(name)) {
      files.push({
        path: `${name}.php`,
        contents: wrapClass(`class ${name}\n{\n}`),
      });
    }
  }
  return files.sort((a, b) => a.path.localeCompare(b.path));
}
